import { type InsertCollege } from "@workspace/db";

// Popular universities that might be missing from College Scorecard API
export const popularColleges: InsertCollege[] = [
  {
    name: "Kennesaw State University",
    location: "Kennesaw, Georgia, United States",
    country: "United States",
    state: "Georgia",
    city: "Kennesaw",
    tuition: 21842,
    acceptanceRate: 65,
    graduationRate: 45,
    type: "public",
    sportsPrograms: ["Football", "Basketball", "Baseball", "Soccer", "Tennis", "Golf", "Track and Field", "Cross Country", "Softball", "Volleyball"],
    academicLevel: "medium",
    scholarships: ["Academic Merit Scholarships", "Need-Based Aid", "Athletic Scholarships", "Georgia HOPE Scholarship"],
    walkOnAvailable: true,
    website: "https://www.kennesaw.edu",
    description: "Kennesaw State University is a public research university located in Kennesaw, Georgia. Known for strong programs in business, education, engineering, and the arts. One of the fastest-growing universities in Georgia with excellent career services and modern facilities.",
    rating: 4
  },
  {
    name: "University of Central Florida",
    location: "Orlando, Florida, United States", 
    country: "United States",
    state: "Florida",
    city: "Orlando",
    tuition: 22467,
    acceptanceRate: 44,
    graduationRate: 73,
    type: "public",
    sportsPrograms: ["Football", "Basketball", "Baseball", "Soccer", "Tennis", "Golf", "Track and Field", "Swimming", "Volleyball"],
    academicLevel: "high",
    scholarships: ["Pegasus Gold Scholarship", "Academic Excellence Scholarships", "Need-Based Aid", "Athletic Scholarships"],
    walkOnAvailable: true,
    website: "https://www.ucf.edu",
    description: "The University of Central Florida is a major public research university known for innovation in education and research. Strong programs in engineering, business, medicine, and hospitality management. One of the largest universities in the United States.",
    rating: 4
  },
  {
    name: "Arizona State University",
    location: "Tempe, Arizona, United States",
    country: "United States", 
    state: "Arizona",
    city: "Tempe",
    tuition: 29428,
    acceptanceRate: 88,
    graduationRate: 67,
    type: "public",
    sportsPrograms: ["Football", "Basketball", "Baseball", "Soccer", "Tennis", "Golf", "Track and Field", "Swimming", "Wrestling", "Softball"],
    academicLevel: "high",
    scholarships: ["New American University Scholarship", "Academic Excellence Awards", "Need-Based Aid", "Athletic Scholarships"],
    walkOnAvailable: true,
    website: "https://www.asu.edu",
    description: "Arizona State University is a public research university known for innovation and accessibility. Strong programs in business, engineering, journalism, and sustainability. Recognized for online education excellence and entrepreneurship programs.",
    rating: 4
  },
  {
    name: "Florida International University",
    location: "Miami, Florida, United States",
    country: "United States",
    state: "Florida", 
    city: "Miami",
    tuition: 18566,
    acceptanceRate: 58,
    graduationRate: 67,
    type: "public",
    sportsPrograms: ["Football", "Basketball", "Baseball", "Soccer", "Tennis", "Track and Field", "Swimming", "Volleyball"],
    academicLevel: "medium",
    scholarships: ["Presidential Scholarship", "Academic Merit Awards", "Need-Based Aid", "Athletic Scholarships"],
    walkOnAvailable: true,
    website: "https://www.fiu.edu",
    description: "Florida International University is a public research university serving the diverse Miami metropolitan area. Known for strong programs in business, engineering, medicine, and international business. Highly diverse student body with excellent career placement.",
    rating: 4
  },
  {
    name: "University of Texas at Dallas",
    location: "Richardson, Texas, United States",
    country: "United States",
    state: "Texas",
    city: "Richardson", 
    tuition: 14564,
    acceptanceRate: 85,
    graduationRate: 70,
    type: "public",
    sportsPrograms: ["Basketball", "Baseball", "Soccer", "Tennis", "Golf", "Track and Field", "Cross Country", "Softball", "Volleyball"],
    academicLevel: "high",
    scholarships: ["Academic Excellence Scholarship", "National Merit Scholarships", "Need-Based Aid", "Athletic Scholarships"],
    walkOnAvailable: true,
    website: "https://www.utdallas.edu",
    description: "The University of Texas at Dallas is a public research university known for excellence in engineering, computer science, business, and natural sciences. Strong industry connections and high graduate employment rates.",
    rating: 4
  },
  {
    name: "George Mason University",
    location: "Fairfax, Virginia, United States",
    country: "United States",
    state: "Virginia",
    city: "Fairfax",
    tuition: 37584,
    acceptanceRate: 90,
    graduationRate: 69,
    type: "public",
    sportsPrograms: ["Basketball", "Baseball", "Soccer", "Tennis", "Golf", "Track and Field", "Cross Country", "Swimming", "Volleyball"],
    academicLevel: "medium",
    scholarships: ["Presidential Scholarship", "Academic Merit Awards", "Need-Based Aid", "Athletic Scholarships"],
    walkOnAvailable: true,
    website: "https://www.gmu.edu",
    description: "George Mason University is a public research university located in the Washington, D.C. metropolitan area. Known for strong programs in economics, law, computer science, and public policy. Excellent access to internships and career opportunities.",
    rating: 4
  },
  {
    name: "University of Nevada, Las Vegas",
    location: "Las Vegas, Nevada, United States",
    country: "United States",
    state: "Nevada",
    city: "Las Vegas",
    tuition: 25540,
    acceptanceRate: 85,
    graduationRate: 45,
    type: "public",
    sportsPrograms: ["Football", "Basketball", "Baseball", "Soccer", "Tennis", "Golf", "Track and Field", "Swimming", "Volleyball"],
    academicLevel: "medium",
    scholarships: ["Presidential Scholarship", "Academic Merit Awards", "Need-Based Aid", "Athletic Scholarships"],
    walkOnAvailable: true,
    website: "https://www.unlv.edu", 
    description: "The University of Nevada, Las Vegas is a public research university known for hospitality management, business, engineering, and health sciences. Strong industry connections in entertainment, gaming, and tourism.",
    rating: 4
  },
  {
    name: "California State University, Northridge",
    location: "Northridge, California, United States",
    country: "United States",
    state: "California",
    city: "Northridge",
    tuition: 17622,
    acceptanceRate: 91,
    graduationRate: 61,
    type: "public",
    sportsPrograms: ["Basketball", "Baseball", "Soccer", "Tennis", "Golf", "Track and Field", "Swimming", "Volleyball"],
    academicLevel: "medium",
    scholarships: ["Academic Excellence Scholarships", "Need-Based Aid", "Athletic Scholarships", "California Grant Programs"],
    walkOnAvailable: true,
    website: "https://www.csun.edu",
    description: "California State University, Northridge is a public university known for diverse academic programs and strong community connections. Excellence in business, education, engineering, and the arts with affordable education in Los Angeles area.",
    rating: 4
  },
  {
    name: "Portland State University",
    location: "Portland, Oregon, United States",
    country: "United States",
    state: "Oregon", 
    city: "Portland",
    tuition: 27810,
    acceptanceRate: 93,
    graduationRate: 50,
    type: "public",
    sportsPrograms: ["Basketball", "Soccer", "Tennis", "Golf", "Track and Field", "Cross Country", "Softball", "Volleyball"],
    academicLevel: "medium",
    scholarships: ["Presidential Scholarship", "Academic Merit Awards", "Need-Based Aid", "Athletic Scholarships"],
    walkOnAvailable: true,
    website: "https://www.pdx.edu",
    description: "Portland State University is a public research university located in downtown Portland. Known for urban studies, social work, business, and sustainability programs. Strong community engagement and diverse student body.",
    rating: 4
  },
  {
    name: "University of Houston",
    location: "Houston, Texas, United States",
    country: "United States",
    state: "Texas",
    city: "Houston",
    tuition: 26027,
    acceptanceRate: 66,
    graduationRate: 61,
    type: "public", 
    sportsPrograms: ["Football", "Basketball", "Baseball", "Soccer", "Tennis", "Golf", "Track and Field", "Swimming", "Volleyball"],
    academicLevel: "high",
    scholarships: ["Tier One Scholarship", "Academic Excellence Awards", "Need-Based Aid", "Athletic Scholarships"],
    walkOnAvailable: true,
    website: "https://www.uh.edu",
    description: "The University of Houston is a public research university known for engineering, business, law, and energy research. Strong industry connections in the energy capital of the world with excellent career placement rates.",
    rating: 4
  }
];