import type { CareerInspiration } from './ai-inspiration-service';

// Curated fallback content for /api/career-inspiration, used whenever no
// ANTHROPIC_API_KEY is configured (or a Claude call fails). Kept small and
// hand-written rather than generated, since it only needs to cover a
// reasonable spread of fields for random/keyword-matched selection.
export const STATIC_INSPIRATIONS: CareerInspiration[] = [
  {
    careerTitle: 'Software Engineer',
    description: 'Designs and builds the applications, websites, and systems people use every day, turning ideas into working software.',
    whyExciting: 'You get to build things that didn\'t exist yesterday and see people use them immediately — few fields let you go from idea to impact this fast.',
    dailyLife: 'Writing and reviewing code, debugging issues, collaborating with designers and product managers, and shipping features in small, frequent releases.',
    futureOpportunities: 'Demand keeps expanding as more industries digitize, with strong paths into AI/ML, infrastructure, security, or technical leadership.',
    inspiringFact: 'Software developer roles are projected to grow much faster than the average occupation over the next decade.',
    pathToStart: 'Learn a language like Python or JavaScript, build a few small projects, contribute to open source, then apply for internships or entry-level roles.',
    salaryRange: '$70,000 - $150,000 annually',
    relatedFields: ['Technology', 'Data Science', 'Product Management', 'Cybersecurity'],
  },
  {
    careerTitle: 'Registered Nurse',
    description: 'Provides direct patient care, coordinates treatment plans, and is often the primary point of contact between patients and the healthcare system.',
    whyExciting: 'Immediate, tangible impact on people\'s lives, paired with strong job security and the option to specialize in almost any area of medicine.',
    dailyLife: 'Assessing patients, administering treatment, coordinating with doctors, and providing the education and reassurance patients need during difficult moments.',
    futureOpportunities: 'Consistently one of the most in-demand professions, with clear paths to nurse practitioner, specialization, or healthcare administration.',
    inspiringFact: 'Nursing has been rated the most trusted profession in the U.S. for over two decades running.',
    pathToStart: 'Complete an accredited nursing program (ADN or BSN), pass the NCLEX-RN licensing exam, and gain clinical experience in a hospital or clinic setting.',
    salaryRange: '$60,000 - $95,000 annually',
    relatedFields: ['Healthcare', 'Helping Others', 'Science', 'Public Health'],
  },
  {
    careerTitle: 'UX/UI Designer',
    description: 'Shapes how digital products look, feel, and function, making sure technology is intuitive and enjoyable for the people who use it.',
    whyExciting: 'A rare blend of creativity and problem-solving — your work directly shapes how millions of people experience a product.',
    dailyLife: 'User research, wireframing, prototyping in tools like Figma, and working closely with engineers to bring designs to life.',
    futureOpportunities: 'Every company building digital products needs design talent, with growth into design leadership, research, or product strategy.',
    inspiringFact: 'Companies that invest heavily in design have been shown to significantly outperform their industry peers financially.',
    pathToStart: 'Build a portfolio with a few real or redesigned projects, learn a design tool like Figma, and study core UX principles.',
    salaryRange: '$65,000 - $120,000 annually',
    relatedFields: ['Creative Arts', 'Design', 'Technology', 'Psychology'],
  },
  {
    careerTitle: 'Environmental Engineer',
    description: 'Applies engineering principles to solve environmental problems — clean water, air quality, waste management, and sustainable infrastructure.',
    whyExciting: 'Work that directly addresses climate and sustainability challenges, with visible results in the communities you serve.',
    dailyLife: 'Designing systems, running environmental impact assessments, testing samples, and working with regulators and communities.',
    futureOpportunities: 'Growing steadily as climate regulation and renewable infrastructure investment increase worldwide.',
    inspiringFact: 'Environmental engineers have played a direct role in dramatically reducing air and water pollution in major cities over the past 50 years.',
    pathToStart: 'Pursue a degree in environmental or civil engineering, seek internships with environmental consultancies or public agencies.',
    salaryRange: '$60,000 - $105,000 annually',
    relatedFields: ['Environment', 'Sustainability', 'Impact', 'Engineering'],
  },
  {
    careerTitle: 'Data Analyst',
    description: 'Turns raw data into insights that guide business decisions, spotting patterns and trends that aren\'t obvious at first glance.',
    whyExciting: 'Every industry runs on data now, so the skills transfer everywhere — from sports to healthcare to finance.',
    dailyLife: 'Cleaning datasets, building dashboards, running statistical analysis, and presenting findings to non-technical stakeholders.',
    futureOpportunities: 'A natural stepping stone into data science, analytics engineering, or business intelligence leadership.',
    inspiringFact: 'Organizations that are data-driven are significantly more likely to report profitability than those that aren\'t.',
    pathToStart: 'Learn SQL and a tool like Excel or Python/pandas, practice on public datasets, and build a portfolio of analysis projects.',
    salaryRange: '$55,000 - $95,000 annually',
    relatedFields: ['Business', 'Technology', 'Statistics', 'Research'],
  },
  {
    careerTitle: 'High School Teacher',
    description: 'Educates and mentors students, shaping how they think, learn, and approach challenges well beyond the classroom.',
    whyExciting: 'Few careers let you see your direct impact play out over years, as students you taught go on to their own careers and lives.',
    dailyLife: 'Lesson planning, teaching classes, grading, and one-on-one mentoring — with summers typically open for other pursuits.',
    futureOpportunities: 'Steady demand in most regions, with paths into curriculum design, school administration, or educational technology.',
    inspiringFact: 'Studies consistently show that a single great teacher can measurably improve a student\'s long-term life outcomes.',
    pathToStart: 'Earn a bachelor\'s degree in your subject area, complete a teaching credential program, and student-teach before certification.',
    salaryRange: '$45,000 - $75,000 annually',
    relatedFields: ['Education', 'Helping Others', 'Leadership', 'Communication'],
  },
  {
    careerTitle: 'Electrician',
    description: 'Installs, maintains, and repairs the electrical systems that power homes, businesses, and infrastructure.',
    whyExciting: 'Hands-on, in-demand work with a clear path to running your own business, and no risk of being automated away anytime soon.',
    dailyLife: 'Reading blueprints, installing wiring and equipment, troubleshooting electrical issues, and ensuring work meets safety codes.',
    futureOpportunities: 'Strong demand driven by construction, renewable energy installation (like solar), and an aging skilled-trades workforce.',
    inspiringFact: 'Skilled trades like electrical work often out-earn many four-year-degree jobs within the first five years, with no student debt.',
    pathToStart: 'Enroll in a trade school or apprenticeship program, accumulate supervised hours, and pass your state licensing exam.',
    salaryRange: '$50,000 - $90,000 annually',
    relatedFields: ['Skilled Trades', 'Engineering', 'Construction', 'Renewable Energy'],
  },
  {
    careerTitle: 'Marketing Manager',
    description: 'Develops and runs campaigns that connect a company\'s products or mission with the people who need them.',
    whyExciting: 'A mix of creativity, data, and psychology — you get to tell stories and measure exactly how well they land.',
    dailyLife: 'Planning campaigns, analyzing performance data, coordinating with design and sales teams, and adjusting strategy in real time.',
    futureOpportunities: 'Growing demand for digital and data-driven marketers, with paths into brand strategy, growth, or executive leadership.',
    inspiringFact: 'Companies with strong brand consistency and marketing strategy see significantly higher customer retention.',
    pathToStart: 'Start with a business or communications degree (or self-taught digital marketing skills), run a small campaign or side project, and build measurable results.',
    salaryRange: '$60,000 - $110,000 annually',
    relatedFields: ['Business', 'Creative Arts', 'Communication', 'Growth'],
  },
  {
    careerTitle: 'Physical Therapist',
    description: 'Helps patients recover mobility and manage pain after injury, surgery, or illness through hands-on treatment and exercise plans.',
    whyExciting: 'You witness recovery firsthand — patients often walk out able to do things they couldn\'t when they walked in.',
    dailyLife: 'One-on-one patient sessions, designing rehabilitation plans, tracking progress, and coordinating with doctors and specialists.',
    futureOpportunities: 'Demand is rising alongside an aging population, with strong pay and options to open a private practice.',
    inspiringFact: 'Physical therapy is consistently ranked among the most satisfying careers in national workplace surveys.',
    pathToStart: 'Complete a Doctor of Physical Therapy (DPT) program after a relevant bachelor\'s degree, then pass the national licensing exam.',
    salaryRange: '$75,000 - $100,000 annually',
    relatedFields: ['Healthcare', 'Helping Others', 'Science', 'Sports Medicine'],
  },
  {
    careerTitle: 'Cybersecurity Analyst',
    description: 'Protects organizations from digital threats by monitoring systems, investigating breaches, and closing security gaps before attackers find them.',
    whyExciting: 'A constant, high-stakes puzzle — you\'re directly defending real people\'s data and money from active adversaries.',
    dailyLife: 'Monitoring security alerts, investigating suspicious activity, running vulnerability scans, and briefing teams on risk.',
    futureOpportunities: 'One of the fastest-growing tech fields, with a well-documented global shortage of qualified analysts.',
    inspiringFact: 'There are far more open cybersecurity roles worldwide than there are qualified candidates to fill them.',
    pathToStart: 'Learn networking and security fundamentals, get a certification like Security+, and practice in home labs or capture-the-flag competitions.',
    salaryRange: '$70,000 - $130,000 annually',
    relatedFields: ['Technology', 'Cybersecurity', 'Problem Solving', 'Risk Management'],
  },
];
